### ISSUE TITLE
Phaser.Text bug position

### ISSUE THREAD

**Issue by antn9x** [PhaserEditor2D/PhaserEditor#56]
![1](https://user-images.githubusercontent.com/2052604/31110338-7e83d4f8-a830-11e7-823f-490d5e926dcf.PNG)
![2](https://user-images.githubusercontent.com/2052604/31110339-7f4831b8-a830-11e7-8804-3e93688db2de.PNG)

It's not the same result form design to Webview.

**Comment by boniatillo-com** [comment]
Hi @antn9x 

Please, can you attach here that green bar image to test it myself? Also, please tell me the font style.
However, the whole font thing is not going to be exact because the scene editor uses JavaFX and could render the fonts in another way. But it would be great if I can test it.

**Comment by antn9x** [comment]
[UTM AvoBold.zip](https://github.com/boniatillo-com/PhaserEditor/files/1354339/UTM.AvoBold.zip)
![slot_bg](https://user-images.githubusercontent.com/2052604/31156216-43f63d6e-a8dd-11e7-8f54-f0adcc0e5fd4.png)

I used this font, please help to check. 
Thanks.

**Comment by boniatillo-com** [comment]
Good, I will check now thanks.

For custom fonts you have to follow these steps:

- Install the font on your OS.
- Load the font in the index.html of your game.

**Comment by boniatillo-com** [comment]
I can reproduce the error. I am working on it. Thanks!

**Comment by boniatillo-com** [comment]
Fixed:

In editor:

![image](https://user-images.githubusercontent.com/12187299/31195263-b7c31e1c-a917-11e7-8914-36a8e7f8c344.png)

In game:

![image](https://user-images.githubusercontent.com/12187299/31195284-c7e476f6-a917-11e7-8442-b9882abc7154.png)

**Comment by antn9x** [comment]
It' still not work for my custom font, please check with my attached font.
Thanks.

**Comment by antn9x** [comment]
More bug here: Display in canvas State and Prefab (group) is difference.
I used Right align.
![3](https://user-images.githubusercontent.com/2052604/31217116-14428c54-a9e0-11e7-8d26-6911fa856b12.PNG)
![4](https://user-images.githubusercontent.com/2052604/31217123-16bda5d6-a9e0-11e7-90f7-b25dcc184e73.PNG)

**Comment by boniatillo-com** [comment]
Please, can you explain more what is "right align"? Are you using the `alignIn` method of Phaser in your game code?

**Comment by antn9x** [comment]
![image](https://user-images.githubusercontent.com/2052604/31259452-e55da4e6-aa70-11e7-9415-a2ac9780a767.png)
I mean this, may be it will suggest you some things to fix position bug.

**Comment by boniatillo-com** [comment]
I will take a look.

**Comment by boniatillo-com** [comment]
I can reproduce the bug. However, I suspect it is not a bug, it is a compatibility issue. In the editor, we use JavaFX to compose the scene but it seems that fonts are not rendered in the same way than in browsers:

Editor:

![image](https://user-images.githubusercontent.com/12187299/31285876-81f4c62c-aa8a-11e7-96db-501a9f416f94.png)

Browser:

![image](https://user-images.githubusercontent.com/12187299/31285928-9da4a0a4-aa8a-11e7-9fdb-0df357a1196e.png)

The first line in the browser is pure HTML, without Phaser.

Note the texts are wider in the browser. I should keep investigating. By the way, update to the last changes, there was a bug with the size of the font, we were using px instead of pt. The height of the texts are consistent, only the width is different.

**Comment by boniatillo-com** [comment]
it is pretty strange, when I use "px", only the height is well, when I use "pt" only the width.

**Comment by boniatillo-com** [comment]
In the last changes, it looks much better, but it is not perfect yet. I was looking into the Phaser codes, and it does a custom bounds computation, I have to mimic it.

**Comment by PhaserEditor2D** [comment]
Too much effort to be implemented for v1 (that is based on JavaFX).
